# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CanzoneInTappa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosik.Canzone')),
            ],
        ),
        migrations.CreateModel(
            name='Tappa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citta', models.CharField(max_length=64)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64, null=True)),
                ('citta', models.CharField(blank=True, max_length=64, null=True)),
                ('provincia', models.CharField(blank=True, max_length=64, null=True)),
                ('nazione', models.CharField(default='Italia', max_length=64)),
                ('artista', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotoCanzoneInTappa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canzoneInTappa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosik.CanzoneInTappa')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosik.Utente')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosik.Utente'),
        ),
        migrations.AddField(
            model_name='tappa',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosik.Tour'),
        ),
        migrations.AddField(
            model_name='canzoneintappa',
            name='tappa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosik.Tappa'),
        ),
        migrations.AddField(
            model_name='canzone',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choosik.Utente'),
        ),
        migrations.AlterUniqueTogether(
            name='votocanzoneintappa',
            unique_together=set([('utente', 'canzoneInTappa')]),
        ),
        migrations.AlterUniqueTogether(
            name='tour',
            unique_together=set([('nome', 'artista')]),
        ),
        migrations.AlterUniqueTogether(
            name='tappa',
            unique_together=set([('citta', 'data', 'tour')]),
        ),
        migrations.AlterUniqueTogether(
            name='canzoneintappa',
            unique_together=set([('canzone', 'tappa')]),
        ),
        migrations.AlterUniqueTogether(
            name='canzone',
            unique_together=set([('titolo', 'autore')]),
        ),
    ]
