# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choosik', '0002_auto_20161026_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='user',
        ),
        migrations.AddField(
            model_name='utente',
            name='password',
            field=models.CharField(default='password', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utente',
            name='username',
            field=models.CharField(default='password', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
